# syntax=docker/dockerfile:1
FROM node:26-alpine@sha256:aadf416b2cdce311a8811ba3f0608a61b77dbf997500e2eafe781b51f6a0b019

RUN apk add --no-cache libc6-compat

WORKDIR /app

ENV PNPM_HOME=/pnpm \
    PATH=/pnpm:$PATH \
    NEXT_TELEMETRY_DISABLED=1

RUN corepack enable
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile
RUN chown -R node:node /app

USER node

EXPOSE 3001

ENV HOSTNAME=0.0.0.0 \
    PORT=3001 \
    WATCHPACK_POLLING=true \
    CHOKIDAR_USEPOLLING=true

CMD ["pnpm", "dev"]
