# syntax=docker/dockerfile:1
FROM node:22-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

ENV PUPPETEER_SKIP_DOWNLOAD=true \
    NEXT_TELEMETRY_DISABLED=1

COPY package.json package-lock.json* ./
RUN npm ci

EXPOSE 3001

ENV HOSTNAME=0.0.0.0 \
    PORT=3001 \
    WATCHPACK_POLLING=true \
    CHOKIDAR_USEPOLLING=true

CMD ["npm", "run", "dev"]
